services:
  zentinel-backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: zentinel-backend
    ports:
      - "3666:3666"
    volumes:
      - ./apps/backend/zentinel.db:/app/apps/backend/zentinel.db
      - C:\Users\edu\Desktop:/root
    environment:
      - PORT=3666
      - NODE_ENV=production
    restart: always

  zentinel-frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: zentinel-frontend
    ports:
      - "8888:80"
    depends_on:
      - zentinel-backend
    restart: always
